### PR TITLE
Netcdf validator

### PR DESCRIPTION
**Pull request by huard**
# Overview

Adds a validator for netCDF files. I don't know if this is useful... I was just trying to understand the code and see how to improve netCDF support. 

Some commits from ldperron and cehbrecht seem to have made their way by mistake. If the PR is useful, I'll clean it up. 

# Related Issue / Discussion

# Additional Information

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [x] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by huard** [comment]
In my PR, for now the href to the opendap link is saved into the `data` attribute. The `file` attribute is a file storing the link, not the netCDF file itself. Should asking for the file attribute trigger a download ?

**Comment by cehbrecht** [comment]
@huard I have reviewed your PR and sure it is useful to have a NetCDF file validator. I would like to keep the `master` branch as a mirror of the `pywps/master`, so it is easier for me to create patches. I have merged your PR to the [dev-netcdf-validator](https://github.com/bird-house/pywps/tree/dev-netcdf-validator) branch.

I have made some fixes and changes on that branch:
* merged with latest pywps/master
* pep8
* fixed tests 
* renamed `requirements-nc.txt` to `requirements-extra.txt`

Probably `gdal` is also capable to validate NetCDF and OpenDAP ... but for us Python `netcdf4` is more convenient, so I would keep it as an extra (or optional?)) requirement.

With your PR you already introduce a solution for handling OpenDAP with pywps (https://github.com/geopython/pywps/issues/152). I would prefer a separate PR for OpenDAP.

Please make a PR to pywps :)

**Review by cehbrecht — CHANGES_REQUESTED** [review]
Separate NetCDF Validator and OpenDAP handling. Make a PR to pywps/master.

**Comment by cehbrecht** [comment]
@huard I have overseen your question:

> In my PR, for now the href to the opendap link is saved into the data attribute. The file attribute is a file storing the link, not the netCDF file itself. Should asking for the file attribute trigger a download ?

This is related to the OpenDAP handling (https://github.com/geopython/pywps/issues/152). First, I would keep the URL as the file attribute of the complex parameter. I think that will work with the Python `netcdf4` library in the user process code, we can have a single parameter for NetCDF files and OpenDAP URLs. 

I wouldn't trigger a download on OpenDAP ... usually we don't want the whole file ... especially not when using aggregations. OpenDAP gives us the advantage to access only the parts of the "data-cube" we need.

**Comment by huard** [comment]
Once the IOHandler refactoring is in, I'll submit a PR for the UrlHandler, and then another PR for the netCDF validator.

**Comment by cehbrecht** [comment]
This is integrated in pywps with PR: https://github.com/geopython/pywps/pull/394

closing now.

**Pull request closed without merging**
