### PR TITLE
changelog additions

### PR DESCRIPTION
**Pull request by huard**

### CODE REVIEW

**Comment by huard** [comment]
I suggest we wait for Adam's Laza fix. That's a bug I've introduced, so ideally it would not make it's way in the official release.

**Comment by cehbrecht** [comment]
@huard thanks :)

**Comment by cehbrecht** [comment]
@huard 

> I suggest we wait for Adam's Laza fix. That's a bug I've introduced, so ideally it would not make it's way in the official release.

Can we manage to pull in the bugfix tomorrow? Otherwise we might loose the motion for a release again ...

**Comment by huard** [comment]
See https://github.com/geopython/pywps/pull/431

**Comment by cehbrecht** [comment]
Ok, I check this tomorrow.

**Pull request merged**
